# Generated by Django 4.1.5 on 2023-01-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('name', 'owner')},
        ),
    ]
